[env:esp32-c3-devkitm-1]
platform  = espressif32 @ 6.9.0
board     = esp32-c3-devkitm-1
framework = arduino

; --- Soros port beállítások ---
monitor_speed  = 115200
upload_speed   = 460800
upload_port = COM3              ; FONTOS!!!
monitor_filters = esp32_exception_decoder
board_build.partitions = min_spiffs.csv

; --- ElegantOTA aszinkron mód engedélyezése ---
build_flags =
    -DELEGANTOTA_USE_ESPIFX=1
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=1
    -DCORE_DEBUG_LEVEL=3
    -DWS_MAX_QUEUED_MESSAGES=64
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; --- Függőségek ---
lib_deps =
    ESP32Async/ESPAsyncWebServer
    ;AsyncTCP @ 3.4.10
    ayushsharma82/ElegantOTA
